#102 don't throw 502 if resource isn't found
opentofu/registry-alpha pull request #104
Opened 2023-09-27 15:05 UTC by rumenvasilev

This *should resolve #102.

2023-09-27 16:15 UTC, serdardalgic reviewed
Just some comments and questions about the parts of the code that are changed in this PR. Please feel free to point out if I'm missing something. Probably @Yantrio would be the correct person to ask. :)

2023-09-27 16:15 UTC, serdardalgic commented on src/internal/providers/versions.go
> -			return fmt.Errorf("release not found")
```
                // Fetch the specific release for the given version.
		release, releaseErr := github.FindRelease(tracedCtx, ghClient, namespace, name, version)
		if releaseErr != nil {
			return fmt.Errorf("failed to find release: %w", releaseErr)
		}

		if release == nil {
			return fmt.Errorf("release not found")
		}
```
Just out of curiosity, and I don't have the means to test this function: 
Shouldn't we get a `releaseErr` when the `release` equals to `nil`?  What's could be the case when the GH API doesn't return and error and the returned release is a null object? 🤔

2023-09-27 16:15 UTC, serdardalgic commented on src/internal/providers/versions.go
> +			return &github.ProviderError{Message: "could not find asset to download", Code: http.StatusNotFound}
I wonder why the FindAssetBySuffix doesn't return `assetToDownload, err` and we don't check the error here instead. 🤔

2023-09-28 07:19 UTC, rumenvasilev commented on src/internal/providers/versions.go
> -			return fmt.Errorf("release not found")
I didn’t write this part, but my thinking is, given there are no automated tests established yet, this will protect in the event of panic. Might be the case it would never be null, but, yeah, until there’s a test to ensure that, it’s safer to have that check.

2023-09-28 07:26 UTC, rumenvasilev commented on src/internal/providers/versions.go
> +			return &github.ProviderError{Message: "could not find asset to download", Code: http.StatusNotFound}
Because generally it might not be an error. `FindAssetBySuffix()` is just a loop over a slice and returns result. Not having an entry in the slice is not an error by itself - it's still a result. So it's up to higher level (calling) functions to decide if that's an error or not, which happens here. Keeping the error handling/decision outside keeps the function more generic, easier to test and reuse.

2023-09-28 08:52 UTC, Yantrio commented
Overall I'm a big fan of this type of error handling and it seems to fit well here.

The downside is that I think that this internal package should not be aware of http statuscodes. Would you be able to implement some custom error types for these (or even some const values to use) please?

2023-09-28 12:18 UTC, rumenvasilev commented
> Overall I'm a big fan of this type of error handling and it seems to fit well here.
> 
> The downside is that I think that this internal package should not be aware of http statuscodes. Would you be able to implement some custom error types for these (or even some const values to use) please?

Are you suggesting sentinel errors + the custom implementation here?
I re-used the http definitions bc we import/use that package anyways, so why redefine if already available.

2023-10-01 14:58 UTC, eranelbaz reviewed
Deployed your code to check for issues, found that one over `providerDownload.go`

2023-10-01 14:58 UTC, eranelbaz commented on src/lambda/api/providerDownload.go
> +				return events.APIGatewayProxyResponse{StatusCode: ghErr.Code}, err
```suggestion
				return events.APIGatewayProxyResponse{StatusCode: ghErr.Code}, nil
```
as we already handled that error, we don't want to keep returning it.
this makes the lambda to keep returning 502

2023-10-01 15:06 UTC, eranelbaz requested changes
Marking my comment as Request changes, as without it we still getting 502

2023-10-02 10:48 UTC, rumenvasilev commented
Thanks!
I’ll make the adjustments on Wed, as I have no computer with me these days. If you want to hurry up, feel free to add the changes suggested and move forward.

On 1. Oct 2023, at 5:06 PM, Elbaz ***@***.***> wrote:

﻿

@eranelbaz requested changes on this pull request.

Marking my comment as Request changes, as without it we still getting 502

—
Reply to this email directly, view it on GitHub<https://github.com/opentofu/registry/pull/104#pullrequestreview-1651919217>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA44TWJDODUFEL5KTYB474DX5GBHNANCNFSM6AAAAAA5JQRXBQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-10-02 14:10 UTC, Yantrio commented
Hi @rumenvasilev I've raised #122 on the back of this. It's taken the core concepts here and brought them across to a rebased branch and introduced the fixes recommended by people.

I'd appreciate it if you had time to review <3 Thanks!

2023-10-04 10:03 UTC, closed without merging

2023-10-04 10:03 UTC, rumenvasilev commented
Sure